### PR TITLE
added download prerequisite feature

### LINKED ISSUE #23: prerequisite tools should be installed from script.sh
When checking for required tools if any tool is missing the script throws an error as shown 

the question here is should we install the missing tool instead

there is another question to follow up that is if we install the tools are we suppose to uninstall it when we run `bash kind.sh --clean`

### PR DESCRIPTION
**Pull request by AvineshTripathi**
fixes #23 

cc @eric978

### CODE REVIEW

**Comment by jhveras-avesha** [comment]
@AvineshTripathi Your changes are ok, but you are missing Docker post-installation steps and the rest of the script is failing because of that. Please, take a look at https://docs.docker.com/engine/install/linux-postinstall 

I think adding commands "sudo usermod -aG docker $USER" and "newgrp docker" should suffice

**Comment by AvineshTripathi** [comment]
@jhveras-avesha can you share the error for failing script as for me its not failing

**Comment by jhveras-avesha** [comment]
@AvineshTripathi  Sure:

image

This is on a newly created ubuntu vm where current user is not yet part of the docker group.

**Comment by AvineshTripathi** [comment]
@jhveras-avesha I think now it should be fine

**Comment by jhveras-avesha** [comment]
@AvineshTripathi it's better now but it only works when the playbook run. Shouldn't we also consider the case when the current user has all the tools installed but  doesn't belong to the docker group? I was thinking of doing something like this:

`if id -nGz "$USER" | grep -qzxF "$GROUP"
then
    echo User \`$USER\' belongs to group \`$GROUP\'
else
    sudo usermod -aG docker $USER
    newgrp docker # I think this command might interrupt the execution of the script
fi`

What do you think?

**Comment by AvineshTripathi** [comment]
isn't user suppose to put docker in a group a mandatory step if not then we should consider this

**Comment by jhveras-avesha** [comment]
@AvineshTripathi Alright, let's throw an error. I think it should be good for now.

**Review by jhveras-avesha — APPROVED** [review]

**Comment by AvineshTripathi** [comment]
Do you want me to add this in the same PR or add a new pr or creating a good-first-issue so that others could take

**Comment by jhveras-avesha** [comment]
@AvineshTripathi please add it to this PR

**Comment by AvineshTripathi** [comment]
Sorry for the delay I ll add that in the PR by Tom, however  the mentioned code for detecting the user inside group is still not general for all the platform so I am finding one for the same

**Comment by AvineshTripathi** [comment]
@jhveras-avesha I have added the check please have a look

**Comment by jhveras-avesha** [comment]
Hi @AvineshTripathi I've tested your changes and the work ok. I'm going to approve this merge

**Review by jhveras-avesha — APPROVED** [review]

**Pull request merged**
