### PR TITLE
add mushop example

### PR DESCRIPTION
**Pull request by kmjayadeep**
Added mushop on slice as another example

### CODE REVIEW

**Comment by eric978** [comment]
LGTM.   Thanks for pulling mushop together!

**Review by eric978 — APPROVED** [review]

**Review by KRANTHI0918 — APPROVED** [review]

**Review by eric978 — COMMENTED** [review]
Actually, should this be up a level (not under kind but just a dir under examples)?

**Comment by kmjayadeep** [comment]
> Actually, should this be up a level (not under kind but just a dir under examples)?

Makes sense. But I'm wondering why the `bookinfo` example is inside `kind` folder?

**Comment by eric978** [comment]
The bookinfo example depends of the kind.sh example environment (at least
as written I don't think it's standalone).    Is mushop also dependent on
the kind.sh 3-cluster environment?   If so, then maybe it does belong there
too?

**Comment by kmjayadeep** [comment]
@eric978 nope, mushop is independent of kind envirnment. I have moved it to root folder

**Pull request merged**
